server:
  port: 9000
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # ???????????????????????????
      routes:
        # ??????????????
        - id: gateway-servicea
          # ?????????????
          uri: http://localhost:8082
          # ????
          predicates:
            # Path Route Predicate Factory ????? /gateway/provider/** ??????????? http://localhost:9024 ??uri?
            - Path=/gateway/servicea/**
            # Weight Route Predicate Factory ???????????????????????80%
            # ???group1?????????????
            - Weight=group1, 10
          # ?????????
          filters:
            # StripPrefix????????????1?????/gateway
            - StripPrefix=2

        - id: gateway-serviceb
          uri: http://localhost:8084
          # ????
          predicates:
            - Path=/gateway/serviceb/**
            # Weight Route Predicate Factory?????????????????????20%
            - Weight=group2, 10
          # ?????????
          filters:
            # StripPrefix????????????1?????/gateway
            - StripPrefix=2